In [2]:
!pip install numpy
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
#1: Create a 1D Numpy array of numbers from 0 to 9
import numpy as np
a1=np.array([0,1,2,3,4,5,6,7,8,9])
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#2: Create a 3x3 matrix with values ranging from 0 to 8
a2=np.array([[[0,1,2],[3,4,5], [6,7,8]]])
print(a2)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


In [7]:
#3: Create a 3x3 identity matrix
a3=np.array([[[1,0,0],[0,1,0], [0,0,1]]])
print(a3)

[[[1 0 0]
  [0 1 0]
  [0 0 1]]]


In [35]:
#4: Generate an array of 10 random numbers between 0 and 1
a4=np.random.randint(10)
print(a4)
a=np.random.randint(1,11, size=10)
print(a)
b=np.random.rand(10)
print(b)

6
[ 8  7  1  1  3  6  3 10  3  3]
[0.59043082 0.3898223  0.98827546 0.34780045 0.04466949 0.55218324
 0.65000815 0.2415575  0.64490799 0.15742523]


In [55]:
arr = np.arange(1,20)
print(arr)

#5 Extract all odd numbers from a numpy array
odd= arr[arr%2!=0]
print(odd)

#6 Replace all odd numbers in the array with -1
arr[arr%2!=0]=-1
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[-1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


In [56]:
#7. Reverse the array arr=np.array([10,20,30,40,50])
arr=np.array([10,20,30,40,50])
arr_rev=arr[::-1]
print(arr_rev)

[50 40 30 20 10]


In [ ]:
#8 Compute the mean, median and sd of arr=np.random.randn(100)
arr=np.random.randn(100)
print(arr)
mean=np.mean(arr)
median=np.median(arr)
sd=np.std(arr)
print(f"The mean is: ",mean)
print(f"The mean is: ",median)
print(f"The mean is: ",sd)


[ 0.09424312 -0.0805641  -1.32593032  1.10042332  0.59032159 -0.81051082
 -0.43971423  0.60288788  0.02274227  0.49934363 -0.11362878 -0.79239519
  1.3188836  -0.04022711  1.56179049 -2.38571031  0.69675083 -0.73655821
  0.56879126  0.56761175  0.56623105 -0.4589076   0.20015966  1.13336557
  0.3184065   0.56326566  0.38716906 -0.42581843  1.87891823 -0.12550386
  1.62280004  1.14132607  0.07957866 -0.16408667 -0.55490082  0.39499922
  0.72188316  0.02745184 -0.24722867  0.76403853  0.03050895  0.17393269
 -0.52130056  0.96914243  0.54732662 -0.69407289 -0.21337411 -0.47678126
  0.75061615  1.20449864  0.45779074  0.04200121 -1.56842937 -1.16786958
  0.30670899  0.26663601  0.72015044  0.48233458  0.44548846 -2.96888897
 -3.35246424  0.76621007  1.50646116  2.69248846  0.8693249   1.723378
  1.02779457  0.65063129  0.83515399 -1.85489152 -0.42384479  1.17315152
  0.09131045  1.01437215 -0.594066   -0.98813898 -1.27426087  0.9679116
 -0.11326389  0.47037785 -0.55138775 -0.40681529 -0.62

In [ ]:
#9 Multiply a 3x3 matrix by a 3x1 column vector
"""
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr1=np.array([1,2,3])
arr_multiply=arr1*arr3
#print(arr_multiply)

"""
vector = np.array([[1],[2],[3]])
#print(vector)
matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
#print(matrix)
result= vector * matrix
print(result)

[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


In [ ]:
#10 Normalize a 1D array values between 0 and 1
arr1 = np.array([1, 2, 3, 4, 5])
normal_arr1=(arr1-np.min(arr1))/(np.max(arr1)-np.min(arr1))
print(normal_arr1)

[0.   0.25 0.5  0.75 1.  ]


In [81]:
#11.Return all elements greater than 2 in an array
a=np.array([1,2,3,4,5])
result=a[a>2]
print(result)

[3 4 5]


In [92]:
#12. Count how many elements in a random array are greater than 0.5
a=np.random.randint(10)
count=np.sum(a>0.5)
print(a)
print(f"Number of elements greater than 0.5 are: ", count)

8
Number of elements greater than 0.5 are:  1


In [ ]:
#13 Create a 5x5 matrix with rows ranging from 0 to 4
matrix=np.arange(25)
print(matrix)
print(matrix.reshape(5,5))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
#14 Replace the maximum value in an array with 0
arr=np.array([1,2,3,4,5,6,7,8,9,])
maximum_index=np.argmax(arr)
print(maximum_index)
arr[maximum_index]=0
print(arr)


8
[1 2 3 4 5 6 7 8 0]


In [106]:
#15 Create a checkerboard matrix of 0s and 1s (8x8)
checkerboard=np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2]=1
checkerboard[::2, 1::2]=1
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])